
version: '3.3'

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind 
      device: C:\home\agachet\data\wp_data
      
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind 
      device: C:\home\agachet\data\db_data

networks:
  inception:
    driver: bridge
 
services:
  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    networks:
       - inception
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    tty: true

  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    tty: true

  nginx:
    build: ./srcs/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress